# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Tell Travis CI we're using MySQL
services:
  - mysql
  
cache:
  directories:
    - $HOME/.composer/cache
    
# Define Test Matrix
# WP_VERSION    = WordPress version number (use "master" for SVN trunk)
# WC_VERSION    = WooCommerce Plugin Version (use "master" for SVN trunk)
# WP_MULTISITE  = whether to test multisite (use either "0" or "1")
matrix:
    include:
        
        # Wordpress Master Branch       
        - php: 7.3
          env: WP_VERSION=master    WC_VERSION=4.0.1   WP_MULTISITE=0        
        - php: 7.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          env: WP_VERSION=master    WC_VERSION=3.9.2   WP_MULTISITE=1        

        # Wordpress 5.4 Branch       
        - php: 7.3
          env: WP_VERSION=5.4       WC_VERSION=4.0.1    WP_MULTISITE=1   
        - php: 7.1
          env: WP_VERSION=5.4       WC_VERSION=3.9.2    WP_MULTISITE=0

        # Wordpress 5.3 Branch       
        - php: 7.3
          env: WP_VERSION=5.3       WC_VERSION=4.0.1    WP_MULTISITE=0
        - php: 7.3
          env: WP_VERSION=5.3       WC_VERSION=3.9.2    WP_MULTISITE=0

        # Wordpress 5.2 Branch       
        - php: 7.1
          env: WP_VERSION=5.2       WC_VERSION=3.6.4    WP_MULTISITE=1   
          
        # Wordpress 5.1 Branch       
        - php: 7.1
          env: WP_VERSION=5.1       WC_VERSION=3.6.4    WP_MULTISITE=0
          
    allow_failures:
        - env: WP_VERSION=master    WC_VERSION=4.0.1   WP_MULTISITE=0 
        - env: WP_VERSION=master    WC_VERSION=3.9.2   WP_MULTISITE=1 
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

install:
    # Disable Xdebug ...
    - phpenv config-rm xdebug.ini
      
before_script:
  
    - export PLUGIN_SLUG=$(basename $(pwd))
    
    # Clone Wordpress & Move to Web folder
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/Wordpress
    
    # Install WooCommerce Module
    - git clone --depth=1 --branch="$WC_VERSION" https://github.com/woocommerce/woocommerce.git    /tmp/Wordpress/src/wp-content/plugins/woocommerce

    # Install Wp Multilang Module
    - git clone --depth=1 https://github.com/VaLeXaR/wp-multilang.git       /tmp/Wordpress/src/wp-content/plugins/wp-multilang
    - composer update --no-dev -d /tmp/Wordpress/src/wp-content/plugins/wp-multilang
    
    # Copy Splash Module to Wordpress folder
    - cd ..
    - mv "$PLUGIN_SLUG" "/tmp/Wordpress/src/wp-content/plugins/splash-connector"

    # Configure Wordpress
    - cd /tmp/Wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    
    # Disable Wp Debug (Not to Show notice etc...) 
    - sed -i "s/WP_DEBUG/WP_NO_DEBUG/" wp-tests-config.php
    
    # Move to Splash Plugin Dir
    - cd "/tmp/Wordpress/src/wp-content/plugins/splash-connector"
    
    # With PHP < 7.2 => Remove Phpstan
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.2" ]]; then composer remove phpstan/phpstan --no-update --dev; fi
    # With PHP < 7.2 => Remove Console
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove splash/console --no-update --dev; fi

    # Run Composer
    - composer update 
    # Show Outdated Packages   
    - composer outdated        
